// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Job represents a single scheduled task persisted in SQLite.
 */
export class Job {
    /**
     * Creates a new Job instance.
     * @param {Partial<Job>} [$$source = {}] - The source object to create the Job.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("Name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Name"] = "";
        }
        if (!("Description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Description"] = "";
        }
        if (!("Schedule" in $$source)) {
            /**
             * cron expression e.g. "0 8 * * *"
             * @member
             * @type {string}
             */
            this["Schedule"] = "";
        }
        if (!("Prompt" in $$source)) {
            /**
             * the message to send to the agent
             * @member
             * @type {string}
             */
            this["Prompt"] = "";
        }
        if (!("Enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Enabled"] = false;
        }
        if (!("SaveToMemory" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["SaveToMemory"] = false;
        }
        if (!("Notify" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Notify"] = false;
        }
        if (!("LastRun" in $$source)) {
            /**
             * RFC3339 or nil
             * @member
             * @type {string | null}
             */
            this["LastRun"] = null;
        }
        if (!("NextRunAt" in $$source)) {
            /**
             * RFC3339 or nil
             * @member
             * @type {string | null}
             */
            this["NextRunAt"] = null;
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * RFC3339
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Job instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Job}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Job(/** @type {Partial<Job>} */($$parsedSource));
    }
}
