// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Message is a single conversation turn stored in SQLite.
 */
export class Message {
    /**
     * Creates a new Message instance.
     * @param {Partial<Message>} [$$source = {}] - The source object to create the Message.
     */
    constructor($$source = {}) {
        if (!("ID" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ID"] = 0;
        }
        if (!("Role" in $$source)) {
            /**
             * "user" | "assistant"
             * @member
             * @type {string}
             */
            this["Role"] = "";
        }
        if (!("Content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Content"] = "";
        }
        if (!("ThinkingContent" in $$source)) {
            /**
             * LLM reasoning/thinking process, empty for most messages
             * @member
             * @type {string}
             */
            this["ThinkingContent"] = "";
        }
        if (!("Images" in $$source)) {
            /**
             * data URLs, empty for most messages
             * @member
             * @type {string[]}
             */
            this["Images"] = [];
        }
        if (!("Files" in $$source)) {
            /**
             * attached file names (no content), empty for most messages
             * @member
             * @type {string[]}
             */
            this["Files"] = [];
        }
        if (!("CreatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["CreatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Message instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Message}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("Images" in $$parsedSource) {
            $$parsedSource["Images"] = $$createField4_0($$parsedSource["Images"]);
        }
        if ("Files" in $$parsedSource) {
            $$parsedSource["Files"] = $$createField5_0($$parsedSource["Files"]);
        }
        return new Message(/** @type {Partial<Message>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
