// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivateModelProfile(arg1) {
  return window['go']['main']['App']['ActivateModelProfile'](arg1);
}

export function AddMCPServer(arg1) {
  return window['go']['main']['App']['AddMCPServer'](arg1);
}

export function ChatDirect(arg1, arg2) {
  return window['go']['main']['App']['ChatDirect'](arg1, arg2);
}

export function ChatDirectCollect(arg1, arg2) {
  return window['go']['main']['App']['ChatDirectCollect'](arg1, arg2);
}

export function ClearChatHistory() {
  return window['go']['main']['App']['ClearChatHistory']();
}

export function ConfirmToolExecution(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConfirmToolExecution'](arg1, arg2, arg3);
}

export function CreateCronJob(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateCronJob'](arg1, arg2, arg3, arg4);
}

export function DeleteCronJob(arg1) {
  return window['go']['main']['App']['DeleteCronJob'](arg1);
}

export function DeleteKnowledgeSource(arg1) {
  return window['go']['main']['App']['DeleteKnowledgeSource'](arg1);
}

export function DeleteMCPServer(arg1) {
  return window['go']['main']['App']['DeleteMCPServer'](arg1);
}

export function DeleteModelProfile(arg1) {
  return window['go']['main']['App']['DeleteModelProfile'](arg1);
}

export function DeleteProactiveItem(arg1) {
  return window['go']['main']['App']['DeleteProactiveItem'](arg1);
}

export function EmitEvent(arg1, arg2) {
  return window['go']['main']['App']['EmitEvent'](arg1, arg2);
}

export function ExportChatHistory() {
  return window['go']['main']['App']['ExportChatHistory']();
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetBallPosition(arg1, arg2) {
  return window['go']['main']['App']['GetBallPosition'](arg1, arg2);
}

export function GetChatSize(arg1, arg2) {
  return window['go']['main']['App']['GetChatSize'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetKokoroTTSVoices() {
  return window['go']['main']['App']['GetKokoroTTSVoices']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetMousePosition() {
  return window['go']['main']['App']['GetMousePosition']();
}

export function GetPetSize(arg1, arg2) {
  return window['go']['main']['App']['GetPetSize'](arg1, arg2);
}

export function GetScreenList() {
  return window['go']['main']['App']['GetScreenList']();
}

export function GetScreenSize() {
  return window['go']['main']['App']['GetScreenSize']();
}

export function GetSoundsEnabled() {
  return window['go']['main']['App']['GetSoundsEnabled']();
}

export function GetTTSAutoPlay() {
  return window['go']['main']['App']['GetTTSAutoPlay']();
}

export function GetToolPermissions() {
  return window['go']['main']['App']['GetToolPermissions']();
}

export function GetVoiceAutoSend() {
  return window['go']['main']['App']['GetVoiceAutoSend']();
}

export function ImportKnowledge(arg1) {
  return window['go']['main']['App']['ImportKnowledge'](arg1);
}

export function IsChatVisible() {
  return window['go']['main']['App']['IsChatVisible']();
}

export function IsFirstLaunch() {
  return window['go']['main']['App']['IsFirstLaunch']();
}

export function IsSMSWatcherRunning() {
  return window['go']['main']['App']['IsSMSWatcherRunning']();
}

export function KillToolExecution(arg1) {
  return window['go']['main']['App']['KillToolExecution'](arg1);
}

export function LarkRunCommand(arg1) {
  return window['go']['main']['App']['LarkRunCommand'](arg1);
}

export function LarkStatus() {
  return window['go']['main']['App']['LarkStatus']();
}

export function ListCronJobs() {
  return window['go']['main']['App']['ListCronJobs']();
}

export function ListKnowledgeSources() {
  return window['go']['main']['App']['ListKnowledgeSources']();
}

export function ListLLMModels(arg1, arg2) {
  return window['go']['main']['App']['ListLLMModels'](arg1, arg2);
}

export function ListMCPServers() {
  return window['go']['main']['App']['ListMCPServers']();
}

export function ListModelProfiles() {
  return window['go']['main']['App']['ListModelProfiles']();
}

export function ListOpenRouterModels(arg1, arg2) {
  return window['go']['main']['App']['ListOpenRouterModels'](arg1, arg2);
}

export function ListProactiveItems() {
  return window['go']['main']['App']['ListProactiveItems']();
}

export function MarkWelcomeShown() {
  return window['go']['main']['App']['MarkWelcomeShown']();
}

export function MissingRequiredConfig() {
  return window['go']['main']['App']['MissingRequiredConfig']();
}

export function OpenDirectoryDialog(arg1) {
  return window['go']['main']['App']['OpenDirectoryDialog'](arg1);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function ResetBallPosition(arg1, arg2) {
  return window['go']['main']['App']['ResetBallPosition'](arg1, arg2);
}

export function RunCronJobNow(arg1) {
  return window['go']['main']['App']['RunCronJobNow'](arg1);
}

export function SaveBallPosition(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveBallPosition'](arg1, arg2, arg3, arg4);
}

export function SaveChatSize(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveChatSize'](arg1, arg2, arg3, arg4);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveModelProfile(arg1) {
  return window['go']['main']['App']['SaveModelProfile'](arg1);
}

export function SavePetSize(arg1, arg2, arg3) {
  return window['go']['main']['App']['SavePetSize'](arg1, arg2, arg3);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SendMessageWithImages(arg1, arg2) {
  return window['go']['main']['App']['SendMessageWithImages'](arg1, arg2);
}

export function SetChatVisible(arg1) {
  return window['go']['main']['App']['SetChatVisible'](arg1);
}

export function SetCronJobEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetCronJobEnabled'](arg1, arg2);
}

export function SetSoundsEnabled(arg1) {
  return window['go']['main']['App']['SetSoundsEnabled'](arg1);
}

export function SetTTSAutoPlay(arg1) {
  return window['go']['main']['App']['SetTTSAutoPlay'](arg1);
}

export function SetToolPermission(arg1, arg2) {
  return window['go']['main']['App']['SetToolPermission'](arg1, arg2);
}

export function SetVoiceAutoSend(arg1) {
  return window['go']['main']['App']['SetVoiceAutoSend'](arg1);
}

export function SetupKokoroTTS() {
  return window['go']['main']['App']['SetupKokoroTTS']();
}

export function SpeakText(arg1) {
  return window['go']['main']['App']['SpeakText'](arg1);
}

export function StartSMSWatcher() {
  return window['go']['main']['App']['StartSMSWatcher']();
}

export function StopGeneration() {
  return window['go']['main']['App']['StopGeneration']();
}

export function StopSMSWatcher() {
  return window['go']['main']['App']['StopSMSWatcher']();
}

export function StopTTS() {
  return window['go']['main']['App']['StopTTS']();
}

export function UpdateCronJob(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateCronJob'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateMCPServer(arg1) {
  return window['go']['main']['App']['UpdateMCPServer'](arg1);
}
