// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ChatService handles AI conversation, streaming, and message history.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as memory$0 from "../memory/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChatDirect streams a proactive AI response for the given prompt without saving to memory.
 * @param {string} prompt
 * @returns {$CancellablePromise<void>}
 */
export function ChatDirect(prompt) {
    return $Call.ByID(306724860, prompt);
}

/**
 * ChatDirectCollect runs a proactive AI generation and collects the full response text.
 * @param {string} prompt
 * @returns {$CancellablePromise<string>}
 */
export function ChatDirectCollect(prompt) {
    return $Call.ByID(2035142942, prompt);
}

/**
 * ClearChatHistory deletes all short-term messages from SQLite and all
 * long-term memory vectors from the chromem collection.
 * @returns {$CancellablePromise<void>}
 */
export function ClearChatHistory() {
    return $Call.ByID(2654844290);
}

/**
 * ExportChatHistory opens a native save dialog and writes the recent 1000
 * messages as plain text to the user-chosen file. Returns nil if the user
 * cancels without choosing a file.
 * @returns {$CancellablePromise<void>}
 */
export function ExportChatHistory() {
    return $Call.ByID(3751636081);
}

/**
 * GetMessages returns recent chat history (up to limit messages).
 * @param {number} limit
 * @returns {$CancellablePromise<memory$0.Message[]>}
 */
export function GetMessages(limit) {
    return $Call.ByID(4270123589, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetMessagesBeforeID returns up to limit messages older than beforeID.
 * @param {number} beforeID
 * @param {number} limit
 * @returns {$CancellablePromise<memory$0.Message[]>}
 */
export function GetMessagesBeforeID(beforeID, limit) {
    return $Call.ByID(2784731491, beforeID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RegenerateLastReply deletes the last assistant message from history and
 * re-runs the agent with the last user message. The response is streamed
 * through the usual chat:token / chat:done / chat:error events.
 * @returns {$CancellablePromise<void>}
 */
export function RegenerateLastReply() {
    return $Call.ByID(625392619);
}

/**
 * SendMessage sends a user message and streams response tokens as Wails events.
 * Events emitted: "chat:token" (string), "chat:done" (""), "chat:error" (string).
 * Any in-flight request is cancelled before starting the new one.
 * @param {string} userInput
 * @returns {$CancellablePromise<void>}
 */
export function SendMessage(userInput) {
    return $Call.ByID(3176176668, userInput);
}

/**
 * SendMessageWithFiles streams an AI response for a user message that may include
 * inline images (data URLs) and/or text file attachments.
 * File contents are appended to the user text before sending to the LLM.
 * Only file names are persisted in memory — not the content.
 * @param {string} userInput
 * @param {string[]} images
 * @param {$models.FileAttachment[]} files
 * @returns {$CancellablePromise<void>}
 */
export function SendMessageWithFiles(userInput, images, files) {
    return $Call.ByID(3263428483, userInput, images, files);
}

/**
 * SendMessageWithImages streams an AI response for a user message that includes
 * one or more inline images encoded as data URLs ("data:image/png;base64,...").
 * Falls back to a plain text message if no valid images are provided.
 * @param {string} userInput
 * @param {string[]} images
 * @returns {$CancellablePromise<void>}
 */
export function SendMessageWithImages(userInput, images) {
    return $Call.ByID(2250269366, userInput, images);
}

/**
 * StopGeneration cancels the current in-flight chat stream.
 * The frontend is responsible for marking the interrupted messages as ghost bubbles.
 * @returns {$CancellablePromise<void>}
 */
export function StopGeneration() {
    return $Call.ByID(4290438577);
}

// Private type creation functions
const $$createType0 = memory$0.Message.createFrom;
const $$createType1 = $Create.Array($$createType0);
