// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService handles app configuration, model profiles, and layout persistence.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

/**
 * ActivateModelProfile switches to the given profile and reinitializes LLM components.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function ActivateModelProfile(id) {
    return $Call.ByID(3111490988, id);
}

/**
 * DeleteModelProfile removes a model profile by id.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteModelProfile(id) {
    return $Call.ByID(682175758, id);
}

/**
 * GetAutoLaunch reports whether Aiko is configured to launch at login.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetAutoLaunch() {
    return $Call.ByID(762666753);
}

/**
 * GetAvailableModels returns a list of available Live2D model names by
 * scanning subdirectories of the bundled live2d assets directory.
 * The special "core" directory is excluded.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAvailableModels() {
    return $Call.ByID(1310611330).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetBallPosition returns the saved ball [x, y] for the given screen resolution,
 * or [-1, -1] if no position has been saved for that resolution yet.
 * @param {number} screenW
 * @param {number} screenH
 * @returns {$CancellablePromise<number[]>}
 */
export function GetBallPosition(screenW, screenH) {
    return $Call.ByID(361219735, screenW, screenH).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetChatSize returns the saved chat bubble [width, height] for the given screen resolution.
 * Returns [0, 0] if no size has been saved for that resolution yet.
 * @param {number} screenW
 * @param {number} screenH
 * @returns {$CancellablePromise<number[]>}
 */
export function GetChatSize(screenW, screenH) {
    return $Call.ByID(1567148426, screenW, screenH).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetConfig returns a snapshot of the current config to the frontend so that
 * concurrent writes via SaveConfig / ActivateModelProfile cannot tear reads.
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function GetConfig() {
    return $Call.ByID(4145926951).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetKokoroTTSVoices returns the static list of Kokoro Chinese voices.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetKokoroTTSVoices() {
    return $Call.ByID(2493668084).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetPetSize returns the saved pet height for the given screen resolution, or 0 if not set or on error.
 * @param {number} screenW
 * @param {number} screenH
 * @returns {$CancellablePromise<number>}
 */
export function GetPetSize(screenW, screenH) {
    return $Call.ByID(1827091647, screenW, screenH);
}

/**
 * GetSoundsEnabled returns whether chat sound effects are enabled.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetSoundsEnabled() {
    return $Call.ByID(1766749310);
}

/**
 * GetTTSAutoPlay returns whether TTS auto-play is enabled.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetTTSAutoPlay() {
    return $Call.ByID(342307227);
}

/**
 * GetVoiceAutoSend returns whether voice messages are sent automatically
 * after the final STT result arrives.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetVoiceAutoSend() {
    return $Call.ByID(1034634144);
}

/**
 * ListLLMModels queries the OpenAI-compatible /v1/models endpoint using the
 * provided baseURL and apiKey (taken directly from the settings form, not the
 * saved config), and returns a sorted list of model IDs.
 * @param {string} baseURL
 * @param {string} apiKey
 * @returns {$CancellablePromise<string[]>}
 */
export function ListLLMModels(baseURL, apiKey) {
    return $Call.ByID(355314252, baseURL, apiKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ListModelProfiles returns all saved model profiles.
 * @returns {$CancellablePromise<config$0.ModelProfile[]>}
 */
export function ListModelProfiles() {
    return $Call.ByID(2706941010).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * ListOpenRouterModels fetches available models from OpenRouter's /api/v1/models/user endpoint.
 * baseURL defaults to "https://openrouter.ai/api/v1" when empty.
 * @param {string} baseURL
 * @param {string} apiKey
 * @returns {$CancellablePromise<string[]>}
 */
export function ListOpenRouterModels(baseURL, apiKey) {
    return $Call.ByID(3659693924, baseURL, apiKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * MissingRequiredConfig returns names of empty required config fields.
 * @returns {$CancellablePromise<string[]>}
 */
export function MissingRequiredConfig() {
    return $Call.ByID(2508614114).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * PingLLM measures the round-trip latency to the active model provider's
 * Base URL by issuing an HTTP HEAD request with a 4-second timeout.
 * Returns elapsed milliseconds, or -1 on any error (empty URL, timeout, etc.).
 * @returns {$CancellablePromise<number>}
 */
export function PingLLM() {
    return $Call.ByID(131408534);
}

/**
 * ResetAvatar removes the custom avatar for the given role ("ai" or "user"),
 * reverting to the built-in default, and emits config:avatar:changed.
 * @param {string} role
 * @returns {$CancellablePromise<void>}
 */
export function ResetAvatar(role) {
    return $Call.ByID(4043949131, role);
}

/**
 * ResetBallPosition deletes the saved ball position for the given screen resolution,
 * causing the pet to return to its default position on next render.
 * @param {number} screenW
 * @param {number} screenH
 * @returns {$CancellablePromise<void>}
 */
export function ResetBallPosition(screenW, screenH) {
    return $Call.ByID(3463878184, screenW, screenH);
}

/**
 * SaveBallPosition persists the ball position for the given screen resolution.
 * @param {number} x
 * @param {number} y
 * @param {number} screenW
 * @param {number} screenH
 * @returns {$CancellablePromise<void>}
 */
export function SaveBallPosition(x, y, screenW, screenH) {
    return $Call.ByID(801309860, x, y, screenW, screenH);
}

/**
 * SaveChatSize persists the chat bubble dimensions for the given screen resolution.
 * @param {number} width
 * @param {number} height
 * @param {number} screenW
 * @param {number} screenH
 * @returns {$CancellablePromise<void>}
 */
export function SaveChatSize(width, height, screenW, screenH) {
    return $Call.ByID(1526394313, width, height, screenW, screenH);
}

/**
 * SaveConfig persists updated config and reinitializes LLM components.
 * LLM init errors are non-fatal (user may save non-LLM settings before configuring the model).
 * @param {config$0.Config | null} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(cfg) {
    return $Call.ByID(2999213856, cfg);
}

/**
 * SaveModelProfile creates or updates a model profile.
 * If the saved profile is the currently active one, cfg is updated in-place so
 * TTS voice/speed/backend changes take effect immediately without a full reinit.
 * @param {config$0.ModelProfile} p
 * @returns {$CancellablePromise<config$0.ModelProfile>}
 */
export function SaveModelProfile(p) {
    return $Call.ByID(2662427068, p).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * SavePetSize persists the pet height for the given screen resolution.
 * @param {number} size
 * @param {number} screenW
 * @param {number} screenH
 * @returns {$CancellablePromise<void>}
 */
export function SavePetSize(size, screenW, screenH) {
    return $Call.ByID(615285794, size, screenW, screenH);
}

/**
 * SetAutoLaunch enables or disables launch-at-login for Aiko.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoLaunch(enabled) {
    return $Call.ByID(2425531333, enabled);
}

/**
 * SetAvatar stores a custom avatar data URL for the given role ("ai" or "user")
 * and emits config:avatar:changed so the frontend can update immediately.
 * @param {string} role
 * @param {string} dataURL
 * @returns {$CancellablePromise<void>}
 */
export function SetAvatar(role, dataURL) {
    return $Call.ByID(672870440, role, dataURL);
}

/**
 * SetSoundsEnabled sets the sounds enabled flag and persists it.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetSoundsEnabled(enabled) {
    return $Call.ByID(3627236674, enabled);
}

/**
 * SetTTSAutoPlay sets TTS auto-play and persists it.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetTTSAutoPlay(enabled) {
    return $Call.ByID(773206007, enabled);
}

/**
 * SetVoiceAutoSend sets the voice auto-send flag and persists it.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetVoiceAutoSend(enabled) {
    return $Call.ByID(866025220, enabled);
}

/**
 * SetupKokoroTTS installs the Kokoro TTS Python environment asynchronously.
 * Progress is reported via notification:show events.
 * @returns {$CancellablePromise<void>}
 */
export function SetupKokoroTTS() {
    return $Call.ByID(330574136);
}

/**
 * SpeakText synthesizes text to speech using the current TTS backend.
 * If text exceeds TTSSummarizeThreshold runes, it is first summarized by the LLM.
 * Audio bytes are emitted as tts:audio (base64 WAV); system speaker plays directly without tts:audio.
 * Events: tts:start, tts:audio (optional), tts:done, tts:error.
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function SpeakText(text) {
    return $Call.ByID(3410170076, text);
}

/**
 * StopTTS cancels any in-flight TTS synthesis or playback.
 * @returns {$CancellablePromise<void>}
 */
export function StopTTS() {
    return $Call.ByID(2565916576);
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = config$0.Config.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = config$0.ModelProfile.createFrom;
const $$createType5 = $Create.Array($$createType4);
