// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * KnowledgeService manages the RAG knowledge base.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * DeleteKnowledgeSource removes all chunks for a given source file.
 * @param {string} source
 * @returns {$CancellablePromise<void>}
 */
export function DeleteKnowledgeSource(source) {
    return $Call.ByID(2004001935, source);
}

/**
 * ImportKnowledge imports a file into the knowledge base.
 * Emits "knowledge:progress" events during import.
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function ImportKnowledge(filePath) {
    return $Call.ByID(2436105436, filePath);
}

/**
 * ListKnowledgeSources returns distinct source filenames in the knowledge base.
 * @returns {$CancellablePromise<string[]>}
 */
export function ListKnowledgeSources() {
    return $Call.ByID(1554652703).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
