// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * MCPService manages MCP server configuration with hot-reload.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcp$0 from "../mcp/models.js";

/**
 * AddMCPServer adds a new MCP server configuration and reloads tools.
 * @param {mcp$0.ServerConfig} cfg
 * @returns {$CancellablePromise<mcp$0.ServerConfig>}
 */
export function AddMCPServer(cfg) {
    return $Call.ByID(979772391, cfg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteMCPServer removes an MCP server configuration by ID and reloads tools.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteMCPServer(id) {
    return $Call.ByID(3592701341, id);
}

/**
 * ListMCPServers returns all configured MCP server entries.
 * @returns {$CancellablePromise<mcp$0.ServerConfig[]>}
 */
export function ListMCPServers() {
    return $Call.ByID(3794995369).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * UpdateMCPServer updates an existing MCP server configuration and reloads tools.
 * @param {mcp$0.ServerConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function UpdateMCPServer(cfg) {
    return $Call.ByID(2075806431, cfg);
}

// Private type creation functions
const $$createType0 = mcp$0.ServerConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
