// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * FileAttachment carries a single text-file attachment from the frontend.
 * Content is the full UTF-8 text of the file; Name and MimeType are metadata only.
 */
export class FileAttachment {
    /**
     * Creates a new FileAttachment instance.
     * @param {Partial<FileAttachment>} [$$source = {}] - The source object to create the FileAttachment.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("mimeType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["mimeType"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileAttachment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileAttachment}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileAttachment(/** @type {Partial<FileAttachment>} */($$parsedSource));
    }
}

/**
 * LinkPreview holds the Open Graph / meta data extracted from a URL.
 */
export class LinkPreview {
    /**
     * Creates a new LinkPreview instance.
     * @param {Partial<LinkPreview>} [$$source = {}] - The source object to create the LinkPreview.
     */
    constructor($$source = {}) {
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("image" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["image"] = "";
        }
        if (!("siteName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["siteName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LinkPreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LinkPreview}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LinkPreview(/** @type {Partial<LinkPreview>} */($$parsedSource));
    }
}

/**
 * MousePosition holds the CSS coordinates of the mouse cursor.
 */
export class MousePosition {
    /**
     * Creates a new MousePosition instance.
     * @param {Partial<MousePosition>} [$$source = {}] - The source object to create the MousePosition.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MousePosition instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MousePosition}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MousePosition(/** @type {Partial<MousePosition>} */($$parsedSource));
    }
}

/**
 * ScreenInfo holds the logical resolution of a screen.
 */
export class ScreenInfo {
    /**
     * Creates a new ScreenInfo instance.
     * @param {Partial<ScreenInfo>} [$$source = {}] - The source object to create the ScreenInfo.
     */
    constructor($$source = {}) {
        if (!("width" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScreenInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScreenInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScreenInfo(/** @type {Partial<ScreenInfo>} */($$parsedSource));
    }
}

/**
 * UpdateInfo holds the result of a CheckUpdate call.
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("current_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current_version"] = "";
        }
        if (!("latest_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latest_version"] = "";
        }
        if (!("download_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["download_url"] = "";
        }
        if (!("has_update" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_update"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

/**
 * VRMModelInfo holds display metadata for a single VRM model file.
 */
export class VRMModelInfo {
    /**
     * Creates a new VRMModelInfo instance.
     * @param {Partial<VRMModelInfo>} [$$source = {}] - The source object to create the VRMModelInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * asset URL usable by the frontend
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("source" in $$source)) {
            /**
             * "builtin" | "user"
             * @member
             * @type {string}
             */
            this["source"] = "";
        }
        if (!("size_kb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["size_kb"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VRMModelInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VRMModelInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VRMModelInfo(/** @type {Partial<VRMModelInfo>} */($$parsedSource));
    }
}
