// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SchedulerService manages cron jobs and proactive message items.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as proactive$0 from "../proactive/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scheduler$0 from "../scheduler/models.js";

/**
 * CreateCronJob creates a new scheduled job.
 * @param {string} name
 * @param {string} description
 * @param {string} schedule
 * @param {string} prompt
 * @param {boolean} saveToMemory
 * @param {boolean} notify
 * @returns {$CancellablePromise<scheduler$0.Job>}
 */
export function CreateCronJob(name, description, schedule, prompt, saveToMemory, notify) {
    return $Call.ByID(3825151399, name, description, schedule, prompt, saveToMemory, notify).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteCronJob removes a scheduled job by ID.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCronJob(id) {
    return $Call.ByID(2242867114, id);
}

/**
 * DeleteProactiveItem cancels a pending proactive reminder by ID.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProactiveItem(id) {
    return $Call.ByID(262353431, id);
}

/**
 * ListCronJobs returns all scheduled jobs.
 * @returns {$CancellablePromise<scheduler$0.Job[]>}
 */
export function ListCronJobs() {
    return $Call.ByID(3214862368).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListProactiveItems returns all pending proactive reminders ordered by trigger time.
 * @returns {$CancellablePromise<proactive$0.Item[]>}
 */
export function ListProactiveItems() {
    return $Call.ByID(2046932203).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * RunCronJobNow fires a scheduled job immediately regardless of its schedule.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function RunCronJobNow(id) {
    return $Call.ByID(3266818620, id);
}

/**
 * SetCronJobEnabled enables or disables a scheduled job.
 * @param {number} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetCronJobEnabled(id, enabled) {
    return $Call.ByID(1828871768, id, enabled);
}

/**
 * UpdateCronJob updates an existing scheduled job.
 * @param {number} id
 * @param {string} name
 * @param {string} description
 * @param {string} schedule
 * @param {string} prompt
 * @param {boolean} saveToMemory
 * @param {boolean} notify
 * @returns {$CancellablePromise<scheduler$0.Job>}
 */
export function UpdateCronJob(id, name, description, schedule, prompt, saveToMemory, notify) {
    return $Call.ByID(674672008, id, name, description, schedule, prompt, saveToMemory, notify).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = scheduler$0.Job.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = proactive$0.Item.createFrom;
const $$createType3 = $Create.Array($$createType2);
