// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService handles app versioning, updates, VRM models, SMS watcher, Lark CLI, and misc system calls.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckUpdate queries the GitHub Releases API and returns update information.
 * @returns {$CancellablePromise<$models.UpdateInfo>}
 */
export function CheckUpdate() {
    return $Call.ByID(3171181153).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteVRMModel removes a user-imported VRM from ~/.aiko/vrm/.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteVRMModel(name) {
    return $Call.ByID(1185453515, name);
}

/**
 * FetchLinkPreview fetches Open Graph / meta tags from the given URL and returns
 * a preview card payload. It times out after 5 s and silently returns an empty
 * preview on any error so the frontend degrades gracefully.
 * @param {string} rawURL
 * @returns {$CancellablePromise<$models.LinkPreview>}
 */
export function FetchLinkPreview(rawURL) {
    return $Call.ByID(1228608340, rawURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetVRMPath returns the asset URL for a given VRM model name.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function GetVRMPath(name) {
    return $Call.ByID(4097474836, name);
}

/**
 * GetVersion returns the version string injected at build time.
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1726835096);
}

/**
 * ImportVRMFile decodes a base64-encoded .vrm file and writes it to
 * ~/.aiko/vrm/{name}. Validates the glTF magic header before writing.
 * @param {string} name
 * @param {string} base64Data
 * @returns {$CancellablePromise<void>}
 */
export function ImportVRMFile(name, base64Data) {
    return $Call.ByID(2488812050, name, base64Data);
}

/**
 * InstallUpdate downloads the DMG at downloadURL, replaces only the main
 * binary inside the running .app bundle, re-signs with the original signing
 * identity (preserving TCC permission grants), then restarts the app.
 * Progress is emitted as "update:progress" Wails events (0–100).
 * @param {string} downloadURL
 * @returns {$CancellablePromise<void>}
 */
export function InstallUpdate(downloadURL) {
    return $Call.ByID(3995848874, downloadURL);
}

/**
 * IsFirstLaunch reports whether the welcome message has never been shown.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsFirstLaunch() {
    return $Call.ByID(3199819385);
}

/**
 * IsSMSWatcherRunning reports whether the SMS watcher is currently active.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsSMSWatcherRunning() {
    return $Call.ByID(2365701318);
}

/**
 * LarkRunCommand executes an arbitrary lark-cli command string and returns stdout.
 * @param {string} args
 * @returns {$CancellablePromise<string>}
 */
export function LarkRunCommand(args) {
    return $Call.ByID(2718546150, args);
}

/**
 * LarkStatus returns the lark-cli authentication status.
 * @returns {$CancellablePromise<string>}
 */
export function LarkStatus() {
    return $Call.ByID(2015324406);
}

/**
 * ListVRMModels returns built-in and user-imported .vrm model metadata.
 * @returns {$CancellablePromise<$models.VRMModelInfo[]>}
 */
export function ListVRMModels() {
    return $Call.ByID(923184277).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * MarkWelcomeShown records that the welcome message has been displayed.
 * @returns {$CancellablePromise<void>}
 */
export function MarkWelcomeShown() {
    return $Call.ByID(191343748);
}

/**
 * StartSMSWatcher enables SMS monitoring, persists the setting, and starts the watcher.
 * @returns {$CancellablePromise<void>}
 */
export function StartSMSWatcher() {
    return $Call.ByID(3857173771);
}

/**
 * StopSMSWatcher disables SMS monitoring, persists the setting, and stops the watcher.
 * @returns {$CancellablePromise<void>}
 */
export function StopSMSWatcher() {
    return $Call.ByID(631401351);
}

// Private type creation functions
const $$createType0 = $models.UpdateInfo.createFrom;
const $$createType1 = $models.LinkPreview.createFrom;
const $$createType2 = $models.VRMModelInfo.createFrom;
const $$createType3 = $Create.Array($$createType2);
