// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ToolService manages tool execution permissions and confirmation flow.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tools$0 from "../tools/models.js";

/**
 * ConfirmToolExecution is called by the frontend when the user approves or rejects
 * a pending tool execution request.
 * @param {string} id
 * @param {boolean} approved
 * @param {string} editedContent
 * @returns {$CancellablePromise<void>}
 */
export function ConfirmToolExecution(id, approved, editedContent) {
    return $Call.ByID(3920096679, id, approved, editedContent);
}

/**
 * GetToolPermissions returns all tool permission rows for the settings UI.
 * @returns {$CancellablePromise<tools$0.PermissionRow[]>}
 */
export function GetToolPermissions() {
    return $Call.ByID(655982481).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * KillToolExecution forcibly terminates a running shell or code execution by its task UUID.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function KillToolExecution(id) {
    return $Call.ByID(2981862645, id);
}

/**
 * SetToolPermission grants or revokes a tool permission.
 * @param {string} toolName
 * @param {boolean} granted
 * @returns {$CancellablePromise<void>}
 */
export function SetToolPermission(toolName, granted) {
    return $Call.ByID(80714428, toolName, granted);
}

// Private type creation functions
const $$createType0 = tools$0.PermissionRow.createFrom;
const $$createType1 = $Create.Array($$createType0);
