// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WindowService manages window state, screen info, and dialog helpers.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AcquireKeyWindow makes the Aiko window the key window so CSS :hover states
 * work while a context menu is open and another app is frontmost.
 * @returns {$CancellablePromise<void>}
 */
export function AcquireKeyWindow() {
    return $Call.ByID(1448292570);
}

/**
 * EmitEvent emits a Wails runtime event with the given name and payload.
 * @param {string} name
 * @param {any} data
 * @returns {$CancellablePromise<void>}
 */
export function EmitEvent(name, data) {
    return $Call.ByID(3470251154, name, data);
}

/**
 * GetMousePosition returns the current mouse cursor position in CSS coordinates.
 * This works even when the app is not focused, enabling eye tracking while unfocused.
 * @returns {$CancellablePromise<$models.MousePosition>}
 */
export function GetMousePosition() {
    return $Call.ByID(1340868505).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetScreenList returns the logical resolution of all connected screens.
 * @returns {$CancellablePromise<$models.ScreenInfo[]>}
 */
export function GetScreenList() {
    return $Call.ByID(3808812719).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetScreenSize returns the primary screen's [width, height] in pixels.
 * @returns {$CancellablePromise<number[]>}
 */
export function GetScreenSize() {
    return $Call.ByID(1137083070).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * IsChatVisible reports whether the chat panel is currently open.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsChatVisible() {
    return $Call.ByID(2703552107);
}

/**
 * OpenDirectoryDialog opens a native directory picker and returns the selected path.
 * @param {string} title
 * @returns {$CancellablePromise<string>}
 */
export function OpenDirectoryDialog(title) {
    return $Call.ByID(2048999144, title);
}

/**
 * OpenFileDialog opens a native file picker and returns the selected path.
 * @param {string} title
 * @param {application$0.FileFilter[]} filters
 * @returns {$CancellablePromise<string>}
 */
export function OpenFileDialog(title, filters) {
    return $Call.ByID(1398901295, title, filters);
}

/**
 * OpenSettings shows and focuses the settings window.
 * @returns {$CancellablePromise<void>}
 */
export function OpenSettings() {
    return $Call.ByID(2749201768);
}

/**
 * ReleaseKeyWindow resigns key-window status, restoring focus to the previous app.
 * @returns {$CancellablePromise<void>}
 */
export function ReleaseKeyWindow() {
    return $Call.ByID(1908377745);
}

/**
 * SetChatVisible updates the tracked chat-panel visibility state.
 * Called by the frontend when the chat bubble is opened or closed.
 * @param {boolean} visible
 * @returns {$CancellablePromise<void>}
 */
export function SetChatVisible(visible) {
    return $Call.ByID(3652535965, visible);
}

// Private type creation functions
const $$createType0 = $models.MousePosition.createFrom;
const $$createType1 = $models.ScreenInfo.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
