// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ServerConfig holds the persisted configuration for one MCP server.
 */
export class ServerConfig {
    /**
     * Creates a new ServerConfig instance.
     * @param {Partial<ServerConfig>} [$$source = {}] - The source object to create the ServerConfig.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("transport" in $$source)) {
            /**
             * "stdio" | "sse" | "http"
             * @member
             * @type {string}
             */
            this["transport"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * stdio only
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("args" in $$source)) {
            /**
             * stdio only
             * @member
             * @type {string[]}
             */
            this["args"] = [];
        }
        if (!("url" in $$source)) {
            /**
             * sse / http
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("headers" in $$source)) {
            /**
             * sse / http optional request headers
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["headers"] = {};
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("created_at" in $$source)) {
            /**
             * RFC3339; string so Wails can generate TS bindings
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ServerConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ServerConfig}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("args" in $$parsedSource) {
            $$parsedSource["args"] = $$createField4_0($$parsedSource["args"]);
        }
        if ("headers" in $$parsedSource) {
            $$parsedSource["headers"] = $$createField6_0($$parsedSource["headers"]);
        }
        return new ServerConfig(/** @type {Partial<ServerConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
