// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the main application struct. All exported methods are Wails bindings.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "./internal/config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcp$0 from "./internal/mcp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as memory$0 from "./internal/memory/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as proactive$0 from "./internal/proactive/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as scheduler$0 from "./internal/scheduler/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tools$0 from "./internal/tools/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AcquireKeyWindow makes the Aiko window the key window so CSS :hover states
 * work while a context menu is open and another app is frontmost.
 * @returns {$CancellablePromise<void>}
 */
export function AcquireKeyWindow() {
    return $Call.ByID(2841894702);
}

/**
 * ActivateModelProfile switches to the given profile and reinitializes LLM components.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function ActivateModelProfile(id) {
    return $Call.ByID(1412417150, id);
}

/**
 * AddMCPServer adds a new MCP server configuration and reloads tools.
 * @param {mcp$0.ServerConfig} cfg
 * @returns {$CancellablePromise<mcp$0.ServerConfig>}
 */
export function AddMCPServer(cfg) {
    return $Call.ByID(1298266315, cfg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ChatDirect streams a proactive AI response for the given prompt without saving to memory.
 * @param {string} prompt
 * @returns {$CancellablePromise<void>}
 */
export function ChatDirect(prompt) {
    return $Call.ByID(650264178, prompt);
}

/**
 * ChatDirectCollect runs a proactive AI generation and collects the full response text.
 * @param {string} prompt
 * @returns {$CancellablePromise<string>}
 */
export function ChatDirectCollect(prompt) {
    return $Call.ByID(2766247732, prompt);
}

/**
 * CheckUpdate queries the GitHub Releases API and returns update information.
 * @returns {$CancellablePromise<$models.UpdateInfo>}
 */
export function CheckUpdate() {
    return $Call.ByID(586574094).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ClearChatHistory deletes all short-term messages from SQLite and all
 * long-term memory vectors from the chromem collection.
 * @returns {$CancellablePromise<void>}
 */
export function ClearChatHistory() {
    return $Call.ByID(1845850356);
}

/**
 * ConfirmToolExecution is called by the frontend when the user approves or rejects
 * a pending tool execution request.
 * @param {string} id
 * @param {boolean} approved
 * @param {string} editedContent
 * @returns {$CancellablePromise<void>}
 */
export function ConfirmToolExecution(id, approved, editedContent) {
    return $Call.ByID(2077501497, id, approved, editedContent);
}

/**
 * CreateCronJob creates a new scheduled job.
 * @param {string} name
 * @param {string} description
 * @param {string} schedule
 * @param {string} prompt
 * @param {boolean} saveToMemory
 * @param {boolean} notify
 * @returns {$CancellablePromise<scheduler$0.Job>}
 */
export function CreateCronJob(name, description, schedule, prompt, saveToMemory, notify) {
    return $Call.ByID(1397500512, name, description, schedule, prompt, saveToMemory, notify).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * DeleteCronJob removes a scheduled job by ID.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCronJob(id) {
    return $Call.ByID(2075932481, id);
}

/**
 * DeleteKnowledgeSource removes all chunks for a given source file.
 * @param {string} source
 * @returns {$CancellablePromise<void>}
 */
export function DeleteKnowledgeSource(source) {
    return $Call.ByID(191042811, source);
}

/**
 * DeleteMCPServer removes an MCP server configuration by ID and reloads tools.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteMCPServer(id) {
    return $Call.ByID(888143801, id);
}

/**
 * DeleteModelProfile removes a model profile by id.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteModelProfile(id) {
    return $Call.ByID(3350795504, id);
}

/**
 * DeleteProactiveItem cancels a pending proactive reminder by ID.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProactiveItem(id) {
    return $Call.ByID(1459600796, id);
}

/**
 * DeleteVRMModel removes a user-imported VRM from ~/.aiko/vrm/.
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function DeleteVRMModel(name) {
    return $Call.ByID(3226856314, name);
}

/**
 * EmitEvent emits a Wails runtime event with the given name and payload.
 * @param {string} name
 * @param {any} data
 * @returns {$CancellablePromise<void>}
 */
export function EmitEvent(name, data) {
    return $Call.ByID(2176953774, name, data);
}

/**
 * ExportChatHistory opens a native save dialog and writes the recent 1000
 * messages as plain text to the user-chosen file. Returns nil if the user
 * cancels without choosing a file.
 * @returns {$CancellablePromise<void>}
 */
export function ExportChatHistory() {
    return $Call.ByID(3213607263);
}

/**
 * FetchLinkPreview fetches Open Graph / meta tags from the given URL and returns
 * a preview card payload. It times out after 5 s and silently returns an empty
 * preview on any error so the frontend degrades gracefully.
 * @param {string} rawURL
 * @returns {$CancellablePromise<$models.LinkPreview>}
 */
export function FetchLinkPreview(rawURL) {
    return $Call.ByID(2147125753, rawURL).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetAutoLaunch reports whether Aiko is configured to launch at login.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetAutoLaunch() {
    return $Call.ByID(3208118679);
}

/**
 * GetAvailableModels returns a list of available Live2D model names by
 * scanning subdirectories of the bundled live2d assets directory.
 * The special "core" directory is excluded.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetAvailableModels() {
    return $Call.ByID(2005304584).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetBallPosition returns the saved ball [x, y] for the given screen resolution,
 * or [-1, -1] if no position has been saved for that resolution yet.
 * @param {number} screenW
 * @param {number} screenH
 * @returns {$CancellablePromise<number[]>}
 */
export function GetBallPosition(screenW, screenH) {
    return $Call.ByID(1426483693, screenW, screenH).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetChatSize returns the saved chat bubble [width, height] for the given screen resolution.
 * Returns [0, 0] if no size has been saved for that resolution yet.
 * @param {number} screenW
 * @param {number} screenH
 * @returns {$CancellablePromise<number[]>}
 */
export function GetChatSize(screenW, screenH) {
    return $Call.ByID(621769792, screenW, screenH).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetConfig returns a snapshot of the current config to the frontend so that
 * concurrent writes via SaveConfig / ActivateModelProfile cannot tear reads.
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function GetConfig() {
    return $Call.ByID(1200034045).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetKokoroTTSVoices returns the static list of Kokoro Chinese voices.
 * @returns {$CancellablePromise<string[]>}
 */
export function GetKokoroTTSVoices() {
    return $Call.ByID(1379687134).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetMessages returns recent chat history (up to limit messages).
 * @param {number} limit
 * @returns {$CancellablePromise<memory$0.Message[]>}
 */
export function GetMessages(limit) {
    return $Call.ByID(3832618599, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetMessagesBeforeID returns up to limit messages older than beforeID.
 * @param {number} beforeID
 * @param {number} limit
 * @returns {$CancellablePromise<memory$0.Message[]>}
 */
export function GetMessagesBeforeID(beforeID, limit) {
    return $Call.ByID(3186529853, beforeID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetMousePosition returns the current mouse cursor position in CSS coordinates.
 * This works even when the app is not focused, enabling eye tracking while unfocused.
 * @returns {$CancellablePromise<$models.MousePosition>}
 */
export function GetMousePosition() {
    return $Call.ByID(768529941).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetPetSize returns the saved pet height for the given screen resolution, or 0 if not set or on error.
 * @param {number} screenW
 * @param {number} screenH
 * @returns {$CancellablePromise<number>}
 */
export function GetPetSize(screenW, screenH) {
    return $Call.ByID(2244962717, screenW, screenH);
}

/**
 * GetScreenList returns all connected screens as ScreenInfo values.
 * @returns {$CancellablePromise<$models.ScreenInfo[]>}
 */
export function GetScreenList() {
    return $Call.ByID(4179416459).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * GetScreenSize returns the primary screen's [width, height] in pixels.
 * @returns {$CancellablePromise<number[]>}
 */
export function GetScreenSize() {
    return $Call.ByID(615827970).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * GetSoundsEnabled returns whether chat sound effects are enabled.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetSoundsEnabled() {
    return $Call.ByID(1243244324);
}

/**
 * GetTTSAutoPlay returns whether TTS auto-play is enabled.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetTTSAutoPlay() {
    return $Call.ByID(2483741737);
}

/**
 * GetToolPermissions returns all tool permission rows for the settings UI.
 * @returns {$CancellablePromise<tools$0.PermissionRow[]>}
 */
export function GetToolPermissions() {
    return $Call.ByID(2949728495).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GetVRMPath returns the asset URL for a given VRM model name.
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function GetVRMPath(name) {
    return $Call.ByID(1507789169, name);
}

/**
 * GetVersion returns the version string injected at build time.
 * @returns {$CancellablePromise<string>}
 */
export function GetVersion() {
    return $Call.ByID(1049863377);
}

/**
 * GetVoiceAutoSend returns whether voice messages are sent automatically
 * after the final STT result arrives.
 * @returns {$CancellablePromise<boolean>}
 */
export function GetVoiceAutoSend() {
    return $Call.ByID(1285664614);
}

/**
 * ImportKnowledge imports a file into the knowledge base.
 * Emits "knowledge:progress" events during import.
 * @param {string} filePath
 * @returns {$CancellablePromise<void>}
 */
export function ImportKnowledge(filePath) {
    return $Call.ByID(1588656792, filePath);
}

/**
 * ImportVRMFile decodes a base64-encoded .vrm file and writes it to
 * ~/.aiko/vrm/{name}. Validates the glTF magic header before writing.
 * @param {string} name
 * @param {string} base64Data
 * @returns {$CancellablePromise<void>}
 */
export function ImportVRMFile(name, base64Data) {
    return $Call.ByID(3638910069, name, base64Data);
}

/**
 * InstallUpdate downloads the DMG at downloadURL, replaces only the main
 * binary inside the running .app bundle, re-signs with the original signing
 * identity (preserving TCC permission grants), then restarts the app.
 * Progress is emitted as "update:progress" Wails events (0–100).
 * @param {string} downloadURL
 * @returns {$CancellablePromise<void>}
 */
export function InstallUpdate(downloadURL) {
    return $Call.ByID(2443992793, downloadURL);
}

/**
 * IsChatVisible returns whether the chat panel is currently visible.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsChatVisible() {
    return $Call.ByID(53623911);
}

/**
 * IsFirstLaunch reports whether the welcome message has never been shown.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsFirstLaunch() {
    return $Call.ByID(3539966690);
}

/**
 * IsSMSWatcherRunning reports whether the SMS watcher is currently active.
 * @returns {$CancellablePromise<boolean>}
 */
export function IsSMSWatcherRunning() {
    return $Call.ByID(597542321);
}

/**
 * KillToolExecution forcibly terminates a running shell or code execution by its task UUID.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function KillToolExecution(id) {
    return $Call.ByID(3441290275, id);
}

/**
 * LarkRunCommand executes an arbitrary lark-cli command string and returns stdout.
 * @param {string} args
 * @returns {$CancellablePromise<string>}
 */
export function LarkRunCommand(args) {
    return $Call.ByID(3250528411, args);
}

/**
 * LarkStatus returns the output of `lark-cli auth status`.
 * @returns {$CancellablePromise<string>}
 */
export function LarkStatus() {
    return $Call.ByID(3262065903);
}

/**
 * ListCronJobs returns all scheduled jobs.
 * @returns {$CancellablePromise<scheduler$0.Job[]>}
 */
export function ListCronJobs() {
    return $Call.ByID(4118595301).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * ListKnowledgeSources returns distinct source filenames in the knowledge base.
 * @returns {$CancellablePromise<string[]>}
 */
export function ListKnowledgeSources() {
    return $Call.ByID(1775768419).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListLLMModels queries the OpenAI-compatible /v1/models endpoint using the
 * provided baseURL and apiKey (taken directly from the settings form, not the
 * saved config), and returns a sorted list of model IDs.
 * @param {string} baseURL
 * @param {string} apiKey
 * @returns {$CancellablePromise<string[]>}
 */
export function ListLLMModels(baseURL, apiKey) {
    return $Call.ByID(541343166, baseURL, apiKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListMCPServers returns all configured MCP server entries.
 * @returns {$CancellablePromise<mcp$0.ServerConfig[]>}
 */
export function ListMCPServers() {
    return $Call.ByID(3510320173).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * ListModelProfiles returns all saved model profiles.
 * @returns {$CancellablePromise<config$0.ModelProfile[]>}
 */
export function ListModelProfiles() {
    return $Call.ByID(4040145872).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * ListOpenRouterModels fetches available models from OpenRouter's /api/v1/models/user endpoint.
 * baseURL defaults to "https://openrouter.ai/api/v1" when empty.
 * @param {string} baseURL
 * @param {string} apiKey
 * @returns {$CancellablePromise<string[]>}
 */
export function ListOpenRouterModels(baseURL, apiKey) {
    return $Call.ByID(3340690998, baseURL, apiKey).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListProactiveItems returns all pending proactive reminders ordered by trigger time.
 * @returns {$CancellablePromise<proactive$0.Item[]>}
 */
export function ListProactiveItems() {
    return $Call.ByID(2596447818).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * ListVRMModels returns built-in and user-imported .vrm model metadata.
 * @returns {$CancellablePromise<$models.VRMModelInfo[]>}
 */
export function ListVRMModels() {
    return $Call.ByID(1405343450).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * MarkWelcomeShown records that the welcome message has been displayed.
 * @returns {$CancellablePromise<void>}
 */
export function MarkWelcomeShown() {
    return $Call.ByID(717572577);
}

/**
 * MissingRequiredConfig returns names of empty required config fields.
 * @returns {$CancellablePromise<string[]>}
 */
export function MissingRequiredConfig() {
    return $Call.ByID(118223780).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * OpenDirectoryDialog opens a native directory picker and returns the selected path.
 * @param {string} title
 * @returns {$CancellablePromise<string>}
 */
export function OpenDirectoryDialog(title) {
    return $Call.ByID(1188724780, title);
}

/**
 * OpenFileDialog opens a native file picker and returns the selected path.
 * @param {string} title
 * @param {application$0.FileFilter[]} filters
 * @returns {$CancellablePromise<string>}
 */
export function OpenFileDialog(title, filters) {
    return $Call.ByID(4196526771, title, filters);
}

/**
 * PingLLM measures the round-trip latency to the active model provider's
 * Base URL by issuing an HTTP HEAD request with a 4-second timeout.
 * Returns elapsed milliseconds, or -1 on any error (empty URL, timeout, etc.).
 * @returns {$CancellablePromise<number>}
 */
export function PingLLM() {
    return $Call.ByID(4052179764);
}

/**
 * RegenerateLastReply deletes the last assistant message from history and
 * re-runs the agent with the last user message. The response is streamed
 * through the usual chat:token / chat:done / chat:error events.
 * @returns {$CancellablePromise<void>}
 */
export function RegenerateLastReply() {
    return $Call.ByID(4108398209);
}

/**
 * ReleaseKeyWindow resigns key-window status, restoring focus to the previous app.
 * @returns {$CancellablePromise<void>}
 */
export function ReleaseKeyWindow() {
    return $Call.ByID(3378705189);
}

/**
 * ResetAvatar removes the custom avatar for the given role ("ai" or "user"),
 * reverting to the built-in default, and emits config:avatar:changed.
 * @param {string} role
 * @returns {$CancellablePromise<void>}
 */
export function ResetAvatar(role) {
    return $Call.ByID(1404338513, role);
}

/**
 * ResetBallPosition deletes the saved ball position for the given screen resolution,
 * causing the pet to return to its default position on next render.
 * @param {number} screenW
 * @param {number} screenH
 * @returns {$CancellablePromise<void>}
 */
export function ResetBallPosition(screenW, screenH) {
    return $Call.ByID(4266248786, screenW, screenH);
}

/**
 * RunCronJobNow fires a scheduled job immediately regardless of its schedule.
 * @param {number} id
 * @returns {$CancellablePromise<void>}
 */
export function RunCronJobNow(id) {
    return $Call.ByID(1791431587, id);
}

/**
 * SaveBallPosition persists the ball position for the given screen resolution.
 * @param {number} x
 * @param {number} y
 * @param {number} screenW
 * @param {number} screenH
 * @returns {$CancellablePromise<void>}
 */
export function SaveBallPosition(x, y, screenW, screenH) {
    return $Call.ByID(124355322, x, y, screenW, screenH);
}

/**
 * SaveChatSize persists the chat bubble dimensions for the given screen resolution.
 * @param {number} width
 * @param {number} height
 * @param {number} screenW
 * @param {number} screenH
 * @returns {$CancellablePromise<void>}
 */
export function SaveChatSize(width, height, screenW, screenH) {
    return $Call.ByID(1801035399, width, height, screenW, screenH);
}

/**
 * SaveConfig persists updated config and reinitializes LLM components.
 * LLM init errors are non-fatal (user may save non-LLM settings before configuring the model).
 * @param {config$0.Config | null} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(cfg) {
    return $Call.ByID(3442292638, cfg);
}

/**
 * SaveModelProfile creates or updates a model profile.
 * If the saved profile is the currently active one, cfg is updated in-place so
 * TTS voice/speed/backend changes take effect immediately without a full reinit.
 * @param {config$0.ModelProfile} p
 * @returns {$CancellablePromise<config$0.ModelProfile>}
 */
export function SaveModelProfile(p) {
    return $Call.ByID(3421967494, p).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType17($result);
    }));
}

/**
 * SavePetSize persists the pet height for the given screen resolution.
 * @param {number} size
 * @param {number} screenW
 * @param {number} screenH
 * @returns {$CancellablePromise<void>}
 */
export function SavePetSize(size, screenW, screenH) {
    return $Call.ByID(2745912064, size, screenW, screenH);
}

/**
 * SendMessage sends a user message and streams response tokens as Wails events.
 * Events emitted: "chat:token" (string), "chat:done" (""), "chat:error" (string).
 * Any in-flight request is cancelled before starting the new one.
 * @param {string} userInput
 * @returns {$CancellablePromise<void>}
 */
export function SendMessage(userInput) {
    return $Call.ByID(1496882310, userInput);
}

/**
 * SendMessageWithFiles streams an AI response for a user message that may include
 * inline images (data URLs) and/or text file attachments.
 * File contents are appended to the user text before sending to the LLM.
 * Only file names are persisted in memory — not the content.
 * @param {string} userInput
 * @param {string[]} images
 * @param {$models.FileAttachment[]} files
 * @returns {$CancellablePromise<void>}
 */
export function SendMessageWithFiles(userInput, images, files) {
    return $Call.ByID(3701558517, userInput, images, files);
}

/**
 * SendMessageWithImages streams an AI response for a user message that includes
 * one or more inline images encoded as data URLs ("data:image/png;base64,...").
 * Falls back to a plain text message if no valid images are provided.
 * @param {string} userInput
 * @param {string[]} images
 * @returns {$CancellablePromise<void>}
 */
export function SendMessageWithImages(userInput, images) {
    return $Call.ByID(4272898556, userInput, images);
}

/**
 * SetAutoLaunch enables or disables launch-at-login for Aiko.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetAutoLaunch(enabled) {
    return $Call.ByID(903093139, enabled);
}

/**
 * SetAvatar stores a custom avatar data URL for the given role ("ai" or "user")
 * and emits config:avatar:changed so the frontend can update immediately.
 * @param {string} role
 * @param {string} dataURL
 * @returns {$CancellablePromise<void>}
 */
export function SetAvatar(role, dataURL) {
    return $Call.ByID(2768178818, role, dataURL);
}

/**
 * SetChatVisible updates the tracked chat-panel visibility state.
 * Called by the frontend when the chat bubble is opened or closed.
 * @param {boolean} visible
 * @returns {$CancellablePromise<void>}
 */
export function SetChatVisible(visible) {
    return $Call.ByID(591430145, visible);
}

/**
 * SetCronJobEnabled enables or disables a scheduled job.
 * @param {number} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetCronJobEnabled(id, enabled) {
    return $Call.ByID(3400108603, id, enabled);
}

/**
 * SetSoundsEnabled sets the sounds enabled flag and persists it.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetSoundsEnabled(enabled) {
    return $Call.ByID(2364549312, enabled);
}

/**
 * SetTTSAutoPlay sets TTS auto-play and persists it.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetTTSAutoPlay(enabled) {
    return $Call.ByID(2408771117, enabled);
}

/**
 * SetToolPermission grants or revokes a tool permission.
 * @param {string} toolName
 * @param {boolean} granted
 * @returns {$CancellablePromise<void>}
 */
export function SetToolPermission(toolName, granted) {
    return $Call.ByID(3086328530, toolName, granted);
}

/**
 * SetVoiceAutoSend sets the voice auto-send flag and persists it.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetVoiceAutoSend(enabled) {
    return $Call.ByID(2902946434, enabled);
}

/**
 * SetupKokoroTTS 在后台异步安装 Kokoro TTS 环境：
 * 1. 创建 Python venv (~/.aiko/tts-venv)
 * 2. 升级 pip
 * 3. 安装 kokoro-onnx、misaki[zh]、soundfile
 * 4. 下载模型文件 kokoro-v1.0.onnx 和 voices-v1.0.bin
 * 进度通过 notification:show 事件汇报。方法立即返回 nil，安装在 goroutine 中运行。
 * @returns {$CancellablePromise<void>}
 */
export function SetupKokoroTTS() {
    return $Call.ByID(2180421586);
}

/**
 * SpeakText synthesizes text to speech using the current TTS backend.
 * If text exceeds TTSSummarizeThreshold runes, it is first summarized by the LLM.
 * Audio bytes are emitted as tts:audio (base64 WAV); system speaker plays directly without tts:audio.
 * Events: tts:start, tts:audio (optional), tts:done, tts:error.
 * @param {string} text
 * @returns {$CancellablePromise<void>}
 */
export function SpeakText(text) {
    return $Call.ByID(2789961602, text);
}

/**
 * StartSMSWatcher enables SMS monitoring, persists the setting, and starts the watcher.
 * @returns {$CancellablePromise<void>}
 */
export function StartSMSWatcher() {
    return $Call.ByID(3645422664);
}

/**
 * StopGeneration cancels the current in-flight chat stream.
 * The frontend is responsible for marking the interrupted messages as ghost bubbles.
 * @returns {$CancellablePromise<void>}
 */
export function StopGeneration() {
    return $Call.ByID(157484847);
}

/**
 * StopSMSWatcher disables SMS monitoring, persists the setting, and stops the watcher.
 * @returns {$CancellablePromise<void>}
 */
export function StopSMSWatcher() {
    return $Call.ByID(1253115170);
}

/**
 * StopTTS cancels any in-flight TTS synthesis or playback.
 * @returns {$CancellablePromise<void>}
 */
export function StopTTS() {
    return $Call.ByID(2529096346);
}

/**
 * UpdateCronJob updates an existing scheduled job.
 * @param {number} id
 * @param {string} name
 * @param {string} description
 * @param {string} schedule
 * @param {string} prompt
 * @param {boolean} saveToMemory
 * @param {boolean} notify
 * @returns {$CancellablePromise<scheduler$0.Job>}
 */
export function UpdateCronJob(id, name, description, schedule, prompt, saveToMemory, notify) {
    return $Call.ByID(3071184251, id, name, description, schedule, prompt, saveToMemory, notify).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * UpdateMCPServer updates an existing MCP server configuration and reloads tools.
 * @param {mcp$0.ServerConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function UpdateMCPServer(cfg) {
    return $Call.ByID(1809162587, cfg);
}

// Private type creation functions
const $$createType0 = mcp$0.ServerConfig.createFrom;
const $$createType1 = $models.UpdateInfo.createFrom;
const $$createType2 = scheduler$0.Job.createFrom;
const $$createType3 = $models.LinkPreview.createFrom;
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = config$0.Config.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = memory$0.Message.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $models.MousePosition.createFrom;
const $$createType11 = $models.ScreenInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = tools$0.PermissionRow.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $Create.Array($$createType2);
const $$createType16 = $Create.Array($$createType0);
const $$createType17 = config$0.ModelProfile.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = proactive$0.Item.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $models.VRMModelInfo.createFrom;
const $$createType22 = $Create.Array($$createType21);
