// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config holds all application settings.
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("LLMBaseURL" in $$source)) {
            /**
             * LLM fields are populated from the active ModelProfile at startup.
             * @member
             * @type {string}
             */
            this["LLMBaseURL"] = "";
        }
        if (!("LLMAPIKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["LLMAPIKey"] = "";
        }
        if (!("LLMModel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["LLMModel"] = "";
        }
        if (!("LLMProvider" in $$source)) {
            /**
             * "openai" or "openrouter"
             * @member
             * @type {string}
             */
            this["LLMProvider"] = "";
        }
        if (!("EmbeddingModel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["EmbeddingModel"] = "";
        }
        if (!("Live2DModel" in $$source)) {
            /**
             * 模型目录名，默认 "hiyori"
             * @member
             * @type {string}
             */
            this["Live2DModel"] = "";
        }
        if (!("RenderBackend" in $$source)) {
            /**
             * "live2d" | "vrm"; default "live2d"
             * @member
             * @type {string}
             */
            this["RenderBackend"] = "";
        }
        if (!("VRMModel" in $$source)) {
            /**
             * selected .vrm filename
             * @member
             * @type {string}
             */
            this["VRMModel"] = "";
        }
        if (!("EmbeddingDim" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["EmbeddingDim"] = 0;
        }
        if (!("EmbeddingProvider" in $$source)) {
            /**
             * "openai" or "openrouter"; default "openai"
             * @member
             * @type {string}
             */
            this["EmbeddingProvider"] = "";
        }
        if (!("EmbeddingBaseURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["EmbeddingBaseURL"] = "";
        }
        if (!("EmbeddingAPIKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["EmbeddingAPIKey"] = "";
        }
        if (!("SystemPrompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SystemPrompt"] = "";
        }
        if (!("ShortTermLimit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ShortTermLimit"] = 0;
        }
        if (!("NudgeInterval" in $$source)) {
            /**
             * 每隔多少轮触发一次 self-growth nudge，0 表示使用默认值 5
             * @member
             * @type {number}
             */
            this["NudgeInterval"] = 0;
        }
        if (!("AllowedPaths" in $$source)) {
            /**
             * file system path whitelist; empty = deny all
             * @member
             * @type {string[]}
             */
            this["AllowedPaths"] = [];
        }
        if (!("ShellTimeout" in $$source)) {
            /**
             * execute_shell timeout in seconds; default 30
             * @member
             * @type {number}
             */
            this["ShellTimeout"] = 0;
        }
        if (!("ShellTrustedCommands" in $$source)) {
            /**
             * 免确认的命令前缀列表
             * @member
             * @type {string[]}
             */
            this["ShellTrustedCommands"] = [];
        }
        if (!("CodeTimeout" in $$source)) {
            /**
             * execute_code timeout in seconds; default 60
             * @member
             * @type {number}
             */
            this["CodeTimeout"] = 0;
        }
        if (!("SMSWatcherEnabled" in $$source)) {
            /**
             * 是否启用 SMS 短信监听（macOS 仅支持）
             * @member
             * @type {boolean}
             */
            this["SMSWatcherEnabled"] = false;
        }
        if (!("VoiceAutoSend" in $$source)) {
            /**
             * 语音识别完成后是否自动发送消息
             * @member
             * @type {boolean}
             */
            this["VoiceAutoSend"] = false;
        }
        if (!("SoundsEnabled" in $$source)) {
            /**
             * 是否启用聊天音效
             * @member
             * @type {boolean}
             */
            this["SoundsEnabled"] = false;
        }
        if (!("SkillsDirs" in $$source)) {
            /**
             * skills 目录列表，支持多个路径
             * @member
             * @type {string[]}
             */
            this["SkillsDirs"] = [];
        }
        if (!("PetSize" in $$source)) {
            /**
             * 宠物显示尺寸（像素），0 表示自动根据屏幕高度计算
             * @member
             * @type {number}
             */
            this["PetSize"] = 0;
        }
        if (!("ChatWidth" in $$source)) {
            /**
             * 聊天框宽度（像素），0 表示使用默认值
             * @member
             * @type {number}
             */
            this["ChatWidth"] = 0;
        }
        if (!("ChatHeight" in $$source)) {
            /**
             * 聊天框高度（像素），0 表示使用默认值
             * @member
             * @type {number}
             */
            this["ChatHeight"] = 0;
        }
        if (!("ActiveProfileID" in $$source)) {
            /**
             * 当前激活的 ModelProfile ID，0 表示未设置
             * @member
             * @type {number}
             */
            this["ActiveProfileID"] = 0;
        }
        if (!("TTSModelDir" in $$source)) {
            /**
             * kokoro 模型目录（空则使用默认 ~/aiko-tts-venv/models）
             * @member
             * @type {string}
             */
            this["TTSModelDir"] = "";
        }
        if (!("TTSVoice" in $$source)) {
            /**
             * 声线名
             * @member
             * @type {string}
             */
            this["TTSVoice"] = "";
        }
        if (!("TTSSpeed" in $$source)) {
            /**
             * 语速，0.5–2.0
             * @member
             * @type {number}
             */
            this["TTSSpeed"] = 0;
        }
        if (!("TTSAutoPlay" in $$source)) {
            /**
             * 外观与交互：chat:done 后自动朗读
             * @member
             * @type {boolean}
             */
            this["TTSAutoPlay"] = false;
        }
        if (!("TTSSummarizeThreshold" in $$source)) {
            /**
             * 摘要字数阈值，默认 200，0 表示禁用摘要
             * @member
             * @type {number}
             */
            this["TTSSummarizeThreshold"] = 0;
        }
        if (!("TTSBackend" in $$source)) {
            /**
             * "kokoro" | ""（系统 say）
             * @member
             * @type {string}
             */
            this["TTSBackend"] = "";
        }
        if (!("ThemeStyle" in $$source)) {
            /**
             * ThemeStyle controls the UI visual style. Values: "liquid-glass" | "frosted".
             * @member
             * @type {string}
             */
            this["ThemeStyle"] = "";
        }
        if (!("JinaAPIKey" in $$source)) {
            /**
             * optional; empty = Jina free tier (~200 req/day)
             * @member
             * @type {string}
             */
            this["JinaAPIKey"] = "";
        }
        if (!("TavilyAPIKey" in $$source)) {
            /**
             * optional; empty = DuckDuckGo fallback
             * @member
             * @type {string}
             */
            this["TavilyAPIKey"] = "";
        }
        if (!("AIAvatar" in $$source)) {
            /**
             * AIAvatar is a data URL for the AI avatar; empty means use the default logo.
             * @member
             * @type {string}
             */
            this["AIAvatar"] = "";
        }
        if (!("UserAvatar" in $$source)) {
            /**
             * UserAvatar is a data URL for the user avatar; empty means use the default icon.
             * @member
             * @type {string}
             */
            this["UserAvatar"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField15_0 = $$createType0;
        const $$createField17_0 = $$createType0;
        const $$createField22_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("AllowedPaths" in $$parsedSource) {
            $$parsedSource["AllowedPaths"] = $$createField15_0($$parsedSource["AllowedPaths"]);
        }
        if ("ShellTrustedCommands" in $$parsedSource) {
            $$parsedSource["ShellTrustedCommands"] = $$createField17_0($$parsedSource["ShellTrustedCommands"]);
        }
        if ("SkillsDirs" in $$parsedSource) {
            $$parsedSource["SkillsDirs"] = $$createField22_0($$parsedSource["SkillsDirs"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

/**
 * ModelProfile holds a named set of LLM credentials and model selection.
 */
export class ModelProfile {
    /**
     * Creates a new ModelProfile instance.
     * @param {Partial<ModelProfile>} [$$source = {}] - The source object to create the ModelProfile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {Provider}
             */
            this["provider"] = Provider.$zero;
        }
        if (!("base_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["base_url"] = "";
        }
        if (!("api_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["api_key"] = "";
        }
        if (!("model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["model"] = "";
        }
        if (!("embedding_model" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["embedding_model"] = "";
        }
        if (!("embedding_dim" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["embedding_dim"] = 0;
        }
        if (!("embedding_inherit" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["embedding_inherit"] = false;
        }
        if (!("embedding_provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["embedding_provider"] = "";
        }
        if (!("embedding_base_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["embedding_base_url"] = "";
        }
        if (!("embedding_api_key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["embedding_api_key"] = "";
        }
        if (!("tts_model_dir" in $$source)) {
            /**
             * kokoro 模型目录（含 onnx/voices bin）
             * @member
             * @type {string}
             */
            this["tts_model_dir"] = "";
        }
        if (!("tts_voice" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tts_voice"] = "";
        }
        if (!("tts_speed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tts_speed"] = 0;
        }
        if (!("tts_backend" in $$source)) {
            /**
             * "kokoro" | ""（系统 say）
             * @member
             * @type {string}
             */
            this["tts_backend"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModelProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModelProfile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModelProfile(/** @type {Partial<ModelProfile>} */($$parsedSource));
    }
}

/**
 * Provider identifies which LLM backend to use.
 * @readonly
 * @enum {string}
 */
export const Provider = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * OpenAI-compatible endpoints
     */
    ProviderOpenAI: "openai",

    /**
     * OpenRouter
     */
    ProviderOpenRouter: "openrouter",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
