// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PermissionRow represents a row in the tool_permissions table for the UI.
 */
export class PermissionRow {
    /**
     * Creates a new PermissionRow instance.
     * @param {Partial<PermissionRow>} [$$source = {}] - The source object to create the PermissionRow.
     */
    constructor($$source = {}) {
        if (!("ToolName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ToolName"] = "";
        }
        if (!("Level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Level"] = "";
        }
        if (!("Granted" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Granted"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PermissionRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PermissionRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PermissionRow(/** @type {Partial<PermissionRow>} */($$parsedSource));
    }
}
