// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearChatHistory() {
  return window['go']['main']['App']['ClearChatHistory']();
}

export function DeleteKnowledgeSource(arg1) {
  return window['go']['main']['App']['DeleteKnowledgeSource'](arg1);
}

export function EmitPetState(arg1) {
  return window['go']['main']['App']['EmitPetState'](arg1);
}

export function GetBallPosition(arg1, arg2) {
  return window['go']['main']['App']['GetBallPosition'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetScreenSize() {
  return window['go']['main']['App']['GetScreenSize']();
}

export function GetToolPermissions() {
  return window['go']['main']['App']['GetToolPermissions']();
}

export function ImportKnowledge(arg1) {
  return window['go']['main']['App']['ImportKnowledge'](arg1);
}

export function ListKnowledgeSources() {
  return window['go']['main']['App']['ListKnowledgeSources']();
}

export function MissingRequiredConfig() {
  return window['go']['main']['App']['MissingRequiredConfig']();
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function SaveBallPosition(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveBallPosition'](arg1, arg2, arg3, arg4);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetToolPermission(arg1, arg2) {
  return window['go']['main']['App']['SetToolPermission'](arg1, arg2);
}

export function ToggleBubble() {
  return window['go']['main']['App']['ToggleBubble']();
}
