// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mcp} from '../models';
import {scheduler} from '../models';
import {config} from '../models';
import {memory} from '../models';
import {tools} from '../models';
import {frontend} from '../models';

export function ActivateModelProfile(arg1:number):Promise<void>;

export function AddMCPServer(arg1:mcp.ServerConfig):Promise<mcp.ServerConfig>;

export function ClearChatHistory():Promise<void>;

export function CreateCronJob(arg1:string,arg2:string,arg3:string,arg4:string):Promise<scheduler.Job>;

export function DeleteCronJob(arg1:number):Promise<void>;

export function DeleteKnowledgeSource(arg1:string):Promise<void>;

export function DeleteMCPServer(arg1:number):Promise<void>;

export function DeleteModelProfile(arg1:number):Promise<void>;

export function ExportChatHistory():Promise<void>;

export function GetAvailableModels():Promise<Array<string>>;

export function GetBallPosition(arg1:number,arg2:number):Promise<Array<number>>;

export function GetConfig():Promise<config.Config>;

export function GetMessages(arg1:number):Promise<Array<memory.Message>>;

export function GetScreenSize():Promise<Array<number>>;

export function GetToolPermissions():Promise<Array<tools.PermissionRow>>;

export function ImportKnowledge(arg1:string):Promise<void>;

export function IsFirstLaunch():Promise<boolean>;

export function LarkRunCommand(arg1:string):Promise<string>;

export function LarkStatus():Promise<string>;

export function ListCronJobs():Promise<Array<scheduler.Job>>;

export function ListKnowledgeSources():Promise<Array<string>>;

export function ListLLMModels(arg1:string,arg2:string):Promise<Array<string>>;

export function ListMCPServers():Promise<Array<mcp.ServerConfig>>;

export function ListModelProfiles():Promise<Array<config.ModelProfile>>;

export function ListOpenRouterModels(arg1:string,arg2:string):Promise<Array<string>>;

export function MarkWelcomeShown():Promise<void>;

export function MissingRequiredConfig():Promise<Array<string>>;

export function OpenFileDialog(arg1:string,arg2:Array<frontend.FileFilter>):Promise<string>;

export function RunCronJobNow(arg1:number):Promise<void>;

export function SaveBallPosition(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveModelProfile(arg1:config.ModelProfile):Promise<config.ModelProfile>;

export function SendMessage(arg1:string):Promise<void>;

export function SetCronJobEnabled(arg1:number,arg2:boolean):Promise<void>;

export function SetToolPermission(arg1:string,arg2:boolean):Promise<void>;

export function UpdateCronJob(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<scheduler.Job>;

export function UpdateMCPServer(arg1:mcp.ServerConfig):Promise<void>;
