// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMCPServer(arg1) {
  return window['go']['main']['App']['AddMCPServer'](arg1);
}

export function ClearChatHistory() {
  return window['go']['main']['App']['ClearChatHistory']();
}

export function CreateCronJob(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateCronJob'](arg1, arg2, arg3, arg4);
}

export function DeleteCronJob(arg1) {
  return window['go']['main']['App']['DeleteCronJob'](arg1);
}

export function DeleteKnowledgeSource(arg1) {
  return window['go']['main']['App']['DeleteKnowledgeSource'](arg1);
}

export function DeleteMCPServer(arg1) {
  return window['go']['main']['App']['DeleteMCPServer'](arg1);
}

export function ExportChatHistory() {
  return window['go']['main']['App']['ExportChatHistory']();
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetBallPosition(arg1, arg2) {
  return window['go']['main']['App']['GetBallPosition'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetMessages(arg1) {
  return window['go']['main']['App']['GetMessages'](arg1);
}

export function GetScreenSize() {
  return window['go']['main']['App']['GetScreenSize']();
}

export function GetToolPermissions() {
  return window['go']['main']['App']['GetToolPermissions']();
}

export function ImportKnowledge(arg1) {
  return window['go']['main']['App']['ImportKnowledge'](arg1);
}

export function IsFirstLaunch() {
  return window['go']['main']['App']['IsFirstLaunch']();
}

export function LarkRunCommand(arg1) {
  return window['go']['main']['App']['LarkRunCommand'](arg1);
}

export function LarkStatus() {
  return window['go']['main']['App']['LarkStatus']();
}

export function ListCronJobs() {
  return window['go']['main']['App']['ListCronJobs']();
}

export function ListKnowledgeSources() {
  return window['go']['main']['App']['ListKnowledgeSources']();
}

export function ListLLMModels(arg1, arg2) {
  return window['go']['main']['App']['ListLLMModels'](arg1, arg2);
}

export function ListMCPServers() {
  return window['go']['main']['App']['ListMCPServers']();
}

export function MarkWelcomeShown() {
  return window['go']['main']['App']['MarkWelcomeShown']();
}

export function MissingRequiredConfig() {
  return window['go']['main']['App']['MissingRequiredConfig']();
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['main']['App']['OpenFileDialog'](arg1, arg2);
}

export function RunCronJobNow(arg1) {
  return window['go']['main']['App']['RunCronJobNow'](arg1);
}

export function SaveBallPosition(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveBallPosition'](arg1, arg2, arg3, arg4);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetCronJobEnabled(arg1, arg2) {
  return window['go']['main']['App']['SetCronJobEnabled'](arg1, arg2);
}

export function SetToolPermission(arg1, arg2) {
  return window['go']['main']['App']['SetToolPermission'](arg1, arg2);
}

export function UpdateCronJob(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateCronJob'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateMCPServer(arg1) {
  return window['go']['main']['App']['UpdateMCPServer'](arg1);
}
