// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {memory} from '../models';
import {frontend} from '../models';

export function DeleteKnowledgeSource(arg1:string):Promise<void>;

export function GetBallPosition(arg1:number,arg2:number):Promise<Array<number>>;

export function GetConfig():Promise<config.Config>;

export function GetMessages(arg1:number):Promise<Array<memory.Message>>;

export function GetScreenSize():Promise<Array<number>>;

export function ImportKnowledge(arg1:string):Promise<void>;

export function ListKnowledgeSources():Promise<Array<string>>;

export function MissingRequiredConfig():Promise<Array<string>>;

export function OpenFileDialog(arg1:string,arg2:Array<frontend.FileFilter>):Promise<string>;

export function SaveBallPosition(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SendMessage(arg1:string):Promise<void>;

export function ToggleBubble():Promise<void>;
