// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {mcp} from '../models';
import {context} from '../models';
import {scheduler} from '../models';
import {main} from '../models';
import {config} from '../models';
import {memory} from '../models';
import {tools} from '../models';
import {proactive} from '../models';
import {frontend} from '../models';

export function ActivateModelProfile(arg1:number):Promise<void>;

export function AddMCPServer(arg1:mcp.ServerConfig):Promise<mcp.ServerConfig>;

export function ChatDirect(arg1:context.Context,arg2:string):Promise<void>;

export function ChatDirectCollect(arg1:context.Context,arg2:string):Promise<string>;

export function ClearChatHistory():Promise<void>;

export function ConfirmToolExecution(arg1:string,arg2:boolean,arg3:string):Promise<void>;

export function CreateCronJob(arg1:string,arg2:string,arg3:string,arg4:string):Promise<scheduler.Job>;

export function DeleteCronJob(arg1:number):Promise<void>;

export function DeleteKnowledgeSource(arg1:string):Promise<void>;

export function DeleteMCPServer(arg1:number):Promise<void>;

export function DeleteModelProfile(arg1:number):Promise<void>;

export function DeleteProactiveItem(arg1:number):Promise<void>;

export function EmitEvent(arg1:string,arg2:any):Promise<void>;

export function ExportChatHistory():Promise<void>;

export function FetchLinkPreview(arg1:string):Promise<main.LinkPreview>;

export function GetAvailableModels():Promise<Array<string>>;

export function GetBallPosition(arg1:number,arg2:number):Promise<Array<number>>;

export function GetChatSize(arg1:number,arg2:number):Promise<Array<number>>;

export function GetConfig():Promise<config.Config>;

export function GetKokoroTTSVoices():Promise<Array<string>>;

export function GetMessages(arg1:number):Promise<Array<memory.Message>>;

export function GetMessagesBeforeID(arg1:number,arg2:number):Promise<Array<memory.Message>>;

export function GetMousePosition():Promise<main.MousePosition>;

export function GetPetSize(arg1:number,arg2:number):Promise<number>;

export function GetScreenList():Promise<Array<main.ScreenInfo>>;

export function GetScreenSize():Promise<Array<number>>;

export function GetSoundsEnabled():Promise<boolean>;

export function GetTTSAutoPlay():Promise<boolean>;

export function GetToolPermissions():Promise<Array<tools.PermissionRow>>;

export function GetVoiceAutoSend():Promise<boolean>;

export function ImportKnowledge(arg1:string):Promise<void>;

export function IsChatVisible():Promise<boolean>;

export function IsFirstLaunch():Promise<boolean>;

export function IsSMSWatcherRunning():Promise<boolean>;

export function KillToolExecution(arg1:string):Promise<void>;

export function LarkRunCommand(arg1:string):Promise<string>;

export function LarkStatus():Promise<string>;

export function ListCronJobs():Promise<Array<scheduler.Job>>;

export function ListKnowledgeSources():Promise<Array<string>>;

export function ListLLMModels(arg1:string,arg2:string):Promise<Array<string>>;

export function ListMCPServers():Promise<Array<mcp.ServerConfig>>;

export function ListModelProfiles():Promise<Array<config.ModelProfile>>;

export function ListOpenRouterModels(arg1:string,arg2:string):Promise<Array<string>>;

export function ListProactiveItems():Promise<Array<proactive.Item>>;

export function MarkWelcomeShown():Promise<void>;

export function MissingRequiredConfig():Promise<Array<string>>;

export function OpenDirectoryDialog(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:string,arg2:Array<frontend.FileFilter>):Promise<string>;

export function ResetBallPosition(arg1:number,arg2:number):Promise<void>;

export function RunCronJobNow(arg1:number):Promise<void>;

export function SaveBallPosition(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SaveChatSize(arg1:number,arg2:number,arg3:number,arg4:number):Promise<void>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveModelProfile(arg1:config.ModelProfile):Promise<config.ModelProfile>;

export function SavePetSize(arg1:number,arg2:number,arg3:number):Promise<void>;

export function SendMessage(arg1:string):Promise<void>;

export function SendMessageWithFiles(arg1:string,arg2:Array<string>,arg3:Array<main.FileAttachment>):Promise<void>;

export function SendMessageWithImages(arg1:string,arg2:Array<string>):Promise<void>;

export function SetChatVisible(arg1:boolean):Promise<void>;

export function SetCronJobEnabled(arg1:number,arg2:boolean):Promise<void>;

export function SetSoundsEnabled(arg1:boolean):Promise<void>;

export function SetTTSAutoPlay(arg1:boolean):Promise<void>;

export function SetToolPermission(arg1:string,arg2:boolean):Promise<void>;

export function SetVoiceAutoSend(arg1:boolean):Promise<void>;

export function SetupKokoroTTS():Promise<void>;

export function SpeakText(arg1:string):Promise<void>;

export function StartSMSWatcher():Promise<void>;

export function StopGeneration():Promise<void>;

export function StopSMSWatcher():Promise<void>;

export function StopTTS():Promise<void>;

export function UpdateCronJob(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string):Promise<scheduler.Job>;

export function UpdateMCPServer(arg1:mcp.ServerConfig):Promise<void>;
